# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Mahdi Baratalipour"
title_separator          : "-"
name                     : &name "Mahdi Baratalipour"
description              : &description "Political theorist and Research Associate (University of Toronto). Focus on citizenship, justice, political theory, and computational text analysis (NLP, semantic analysis, clustering)."
url                      : https://baratalipour.github.io
baseurl                  : ""
repository               : "Baratalipour/Baratalipour.github.io"

author:
  avatar           : "profile.png"
  name             : "Mahdi Baratalipour"
  pronouns         :
  bio              : "Political theorist working on citizenship, justice, and computational analysis of political and legal texts."
  location         : "Toronto, Canada"
  employer         : "University of Toronto Scarborough"
  uri              :
  email            : "m.baratalipour@gmail.com"

  academia         :
  arxiv            :
  googlescholar    :
  inspire-hep      :
  impactstory      :
  orcid            :
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :
  scopus           :
  zotero           :

  bitbucket        :
  codepen          :
  dribbble         :
  github           : "Baratalipour"
  kaggle           :
  stackoverflow    :

  artstation       :
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :
